package com.icure.monitoring.probes.dsl.threshold

import com.icure.monitoring.probes.dsl.comparators.ThresholdValue

/**
 * A functional interface that allow to define a custom reference value for a probe: the value generated by the concrete
 * implementation of this class will be compared by the one generated by the probe and it may trigger an action.
 */
sealed interface Threshold {

    fun getValue(): ThresholdValue?
}