package com.icure.monitoring.model

@Suppress("unused")
enum class MetricsTags(val tagName: String, val queryValue: String) {
    NAMESPACE("location.namespace", "location_namespace"),
    INSTANCE_ID("location.instance.id", "location_instance_id"),
    NODE_ID("location.node.id", "location_node_id"),
    POD_ID("pod.id", "pod_id"),
    METRIC("metric", "metric"),
    TYPE("type", "type"),
    BACKEND("backend", "backend"),
    PATH_CLASS("pathClass", "pathClass"),
    FRONTEND("frontend","frontend"),
    HTTP_METHOD("method", "method"),
    COMPONENT("component", "component"),
    HTTP_STATUS("httpstatus", "httpstatus"),
    COUCHDB_GROUP("couchdb.group", "couchdb_group"),
    COUCHDB_DB("couchdb.db", "couchdb_db"),
    USAGE_GROUP("usage.group", "usage_group"),
    USAGE_METHOD("usage.method", "usage_method"),
    USAGE_PATH("usage.path", "usage_path"),
    CONTAINER_ID("container.id", "container_id"),
    STORAGE_TYPE("storage.type", "storage_type"),
    KRAKEN_GROUP("group", "group"),
    ENTITY_TYPE("entity.type", "entity_type"),
    DISK_NAME("diskName", "diskName"),
    SERIAL_NUMBER("serialNumber", "serialNumber"),
    STORAGE_NAME("storageName", "storageName"),
    HEALTH("health", "health"),
    LOG_LEVEL("log.level", "log_level"),
    OPERATION("operation", "operation"),
    TCP_PORT("tcp.port", "tcp_port"),
    COUCHDB_TASK_TYPE("couchdb.task.type", "couchdb_task_type"),
    COUCHDB_TASK_STATUS("couchdb.task.status", "couchdb_task_status"),
    COUCHDB_TASK_RUN_TIME("couchdb.task.run.time", "couchdb_task_run_time"),
    COUCHDB_TASK_ITEMS("couchdb.task.items", "couchdb_task_items"),
    DESIGN_DOC("designdoc", "designdoc"),
    DESIGN_VIEW("view", "view"),
    NETWORK_INTERFACE("network.interface", "network_interface"),
    URL("url", "url"),
    SERVICE_NAME("service.name", "service_name"),
    REPLICA_ID("replica.id", "replica_id"),
    IMAGE("image", "image"),
}
