package com.icure.monitoring.model

@Suppress("unused")
enum class MetricsTags(val tagName: String, val queryValue: String) {
    NAMESPACE("location.namespace", "location_namespace"),
    INSTANCE_ID("location.instance.id", "location_instance_id"),
    NODE_ID("location.node.id", "location_node_id"),
    POD_ID("pod.id", "pod_id"),
    METRIC("metric", "metric"),
    TYPE("type", "type"),
    BACKEND("backend", "backend"),
    PATH_CLASS("pathClass", "pathClass"),
    FRONTEND("frontend","frontend"),
    HTTP_METHOD("method", "method"),
    COMPONENT("component", "component"),
    HTTP_STATUS("httpstatus", "httpstatus"),
    COUCHDB_GROUP("couchdb.group", "couchdb_group"),
    USAGE_GROUP("usage.group", "usage_group"),
    USAGE_METHOD("usage.method", "usage_method"),
    USAGE_PATH("usage.path", "usage_path"),
    CONTAINER_ID("container.id", "container_id"),
    STORAGE_TYPE("storage.type", "storage_type"),
    KRAKEN_GROUP("group", "group"),
    ENTITY_TYPE("entity.type", "entity_type"),
    DISK_NAME("diskName", "diskName"),
    SERIAL_NUMBER("serialNumber", "serialNumber"),
    STORAGE_NAME("storageName", "storageName"),
    ZPOOL_STORAGE_TOTAL_SIZE("zpool.storage.totalSize", "zpool_storage_totalSize"),
    ZPOOL_STORAGE_TOTAL_ALLOCATED_SPACE("zpool.storage.totalAllocatedPhysicalSpace", "zpool_storage_totalAllocatedPhysicalSpace"),
    ZPOOL_STORAGE_TOTAL_FREE_SPACE("zpool.storage.totalFreeSpace", "zpool_storage_totalFreeSpace"),
    ZPOOL_STORAGE_FRAGMENTATION_PERCENTATION("zpool.storage.fragmentationPercentation", "zpool_storage_fragmentationPercentation"),
    ZPOOL_STORAGE_USED_SPACE_PERCENTAGE("zpool.storage.usedSpacePercentage", "zpool_storage_usedSpacePercentage"),
    ZPOOL_STORAGE_DEDUP_RATIO("zpool.storage.dedupRatio", "zpool_storage_dedupRatio"),
    ZPOOL_STORAGE_HEALTH("zpool.storage.health", "zpool_storage_health"),
    HEALTH("health", "health"),
    LOG_LEVEL("log.level", "log_level"),
    OPERATION("operation", "operation"),
    TCP_PORT("tcp.port", "tcp_port"),
    COUCHDB_TASK_TYPE("couchdb.task.type", "couchdb_task_type"),
    COUCHDB_TASK_STATUS("couchdb.task.status", "couchdb_task_status"),
    COUCHDB_TASK_RUN_TIME("couchdb.task.run.time", "couchdb_task_run_time"),
    COUCHDB_TASK_ITEMS("couchdb.task.items", "couchdb_task_items")
}