[versions]
kotlin = "2.0.0"
micrometer = "1.13.6"
hdrHistogram = "2.2.2"
kotlinxSerialization = "1.7.3"
ktor = "3.0.0"
jupiter = "5.10.3"
mockk = "1.13.12"
kotest = "5.9.1"
apacheCommons = "1.5"

[libraries]
micrometer = { group = "io.micrometer", name = "micrometer-core", version.ref = "micrometer" }
hdrHistogram = { group = "org.hdrhistogram", name = "HdrHistogram", version.ref = "hdrHistogram"}
kotlinxSerialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
ktorClientCore = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktorClientCio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor" }
ktorClientOkHttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktorClientContentNegotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
junit = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "jupiter" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
kotestCore = { group = "io.kotest", name = "kotest-assertions-core-jvm", version.ref = "kotest" }
kotestRunner = { group = "io.kotest", name = "kotest-runner-junit5", version.ref = "kotest" }
apacheRngSimple = { group = "org.apache.commons", name = "commons-rng-simple", version.ref = "apacheCommons" }
apacheRngSampling = { group = "org.apache.commons", name = "commons-rng-sampling", version.ref = "apacheCommons" }
guava = { group = "com.google.guava", name = "guava", version = "33.4.8-jre" }

[bundles]
ktorClient = ["ktorClientCore", "ktorClientCio", "ktorClientOkHttp", "ktorClientContentNegotiation"]

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinxSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
